### ISSUE TITLE
Use generator to automatically template in deployed payload addresses

### ISSUE THREAD

**Issue by reem** [bgd-labs/aave-proposals-v3#52]
This is one of the last "manual" steps remaining in the process of creating a generator-supported AIP and would be great to fully automate.

Potentially this could be done by moving the CreateProposal script into its own file which is generated by using the generator again after deploying the payloads.

Could also wrap the commands needed to deploy all payloads so that there is a single entry point in the generator for this even for multi chain proposals. Potentially storing the deployed addresses in config.json or in an additional json file also added to the proposal directories?

**Comment by sakulstra** [comment]
Interesting idea.
So if i understand you right you essentially would want the playload deployscript to alter the proposal creation script.
I think we need to do some cleanup work first, but imo should be possible 🤔

**Comment by reem** [comment]
Yes, either modify the script or just move the `CreateProposal` contract into its own file that is only generated later on

Goal is to avoid any human steps of copy pasting payload addresses etc.

**Comment by sakulstra** [comment]
we discussed a bit internally and probably the most rational thing to do is switching to create2. That way we can easily validate that what was deployed matches the predicted address.
