### ISSUE TITLE
Add support for `setReserveFreeze` operations to the generator

### ISSUE THREAD

**Issue by reem** [bgd-labs/aave-proposals-v3#57]
Currently this operation isn't exposed in the generator, but is a pretty common thing to do in proposals. Would be nice to have this feature enabled as well.

**Comment by reem** [comment]
Mostly just to avoid any manual human operations, when possible I think it's optimal that the proposals should be generatable entirely from config, so that if any updates are made to the generator or to the params one can just update the config and regenerate without any possibility of human error when combining changes or making manual updates.

**Comment by sakulstra** [comment]
@reem , i misunderstoof before - yes sounds perfectly reasonable to me.
Feel free to create a pr in case you got time - if not we'll pick that up eventually.

**Comment by sakulstra** [comment]
@reem this is now supported (at least for v3) so closing.
